[package]
name = "a"
version = "0.1.0"

build = "build.rs"

[features]
bar = ["a-sys/bar"]

[dependencies.a-sys]
path = "../a-sys"
version = "0.1.0"

[build-dependencies.a-sys]
path = "../a-sys"
version = "0.1.0"
